stages:
  - build
  - deploy

.deploy_to_ecr_base:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash
    - apk add --no-cache curl jq python3 py3-pip
    - pip3 install awscli
    - echo "Logging in to Amazon ECR..."
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"

  script:
    - echo "Building and pushing Docker image to ECR..."
    - docker build -t $ECR_REPO_NAME .
    - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
    - TAGGED_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
    - docker tag $ECR_REPO_NAME:latest $TAGGED_IMAGE
    - docker push $TAGGED_IMAGE
    - docker tag $TAGGED_IMAGE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:latest
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:latest

.deploy_to_ecs_base:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash
    - apk add --no-cache curl jq python3 py3-pip
    - pip3 install awscli
    - echo "Logging in to Amazon ECR..."
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"
  
  script:
    - echo "Stopping all tasks in the ECS cluster..."
    - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --desired-count 0
    - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
    - aws ecs wait services-stable --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME
    - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --desired-count 1
    - docker image prune -af

dev_deploy_to_ecr:
  stage: build
  variables:
    ECR_REPO_NAME: "dev-prebot-py"
  extends: .deploy_to_ecr_base
  only:
    refs:
      - develop

dev_deploy_to_ecs:
  stage: deploy
  variables:
    ECS_CLUSTER_NAME: "DEV-Prebot-Py"
    ECS_SERVICE_NAME: "DEV-Prebot-Py"
  extends: .deploy_to_ecs_base
  only:
    refs:
      - develop

