version: "3.8"
services:
    laravel-docker-aws:
        container_name: laravel-docker-aws-app
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 80:80

